---
version: '3.1'


volumes:
  dbmysql:
  mysql:

services:
  mysql:
    container_name: mysql-db
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - dbmysql:/dbmysql
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - TZ=Europe/Berlin
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --wait-timeout=600 --interactive-timeout=600
    
    
    
  camelan:
    container_name: camelan
    image: maven:3.5.4-jdk-8
    working_dir: /camelan
    command: bash -c "mvn install && mvn spring-boot:run"
    volumes:
      - ./camelan:/camelan
    ports:
      - 7000:7000
    depends_on:
      - mysql

